### ISSUE TITLE
Can't sign up and then sign in

### ISSUE THREAD

**Issue by glafrancefa** [cypress-io/cypress-realworld-app#1106]
After cloning the repository and then doing an npm install and yarn dev, I launch the app and try to sign up and then sign in, but a message says Username or Password is incorrect.

Dev tools shows connection refused. Do I also need to start a backend server on localhost?

**Comment by dgraciamorales** [comment]
Hi @glafrancefa, using **yarn install** instead **npm install** worked for me.
