### ISSUE TITLE
Unable to run parallel with value passed from github actions workflow_dispatch

### ISSUE THREAD

**Issue by gonazmul** [cypress-io/cypress-realworld-app#1199]
The script works fine when I run with hardcoded parameters like below -

        - name: "UI Tests - Chrome"
          uses: cypress-io/github-action@v2
          with:
            browser: chrome
            record: true
            parallel: true
            group: "UI - Chrome"
            spec: cypress/tests/ui/*
          env:
            CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

But it fails when I pass the parameters (browser and spec) value from `workflow_dispatch` input like below -

        - name: "UI Tests - Chrome"
          uses: cypress-io/github-action@v2
          with:
            browser: ${{ github.event.inputs.browser }}
            record: true
            parallel: true
            group: "UI - Chrome"
            spec: ${{ github.event.inputs.spec }}
          env:
            CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

The error message I get is `You passed the --parallel flag, but we do not parallelize tests across different environments.`

From the error message I can see the environment parameters are exactly the same across machine - https://www.screencast.com/t/jLmg2r8rrk

I also tried saving the `workflow_dispatch` inputs into the `$GITHUB_ENV` and then using that env variable as parameters but still the same error.

It's just not supporting the dynamic value.

**Comment by robertguss** [comment]
@gonazmul are you attempting to run your tests against different browsers with different spec files? If so, it is typically best to create a separate job to run your specific tests against a specific browser. 

Help me understand why these values need to be dynamic?

**Comment by gonazmul** [comment]
I want to run them using this `Run workflow` button with the ability to pass different browser and spec paths [like here](https://www.screencast.com/t/ahrWe1ebGo). They should be and are the same parameters across all machines (as you can see in the [screenshot here](https://www.screencast.com/t/jLmg2r8rrk)). It fails and says I am passing different parameters when it's in fact the same.

The combination of spec files could be endless depending on what test I want to execute. That's why I want to use the inputs from `workflow_dispatch` to feed into the environment parameters

**Comment by gonazmul** [comment]
@robertguss Well, I figured it out. I had to wrap the variables in quotes like below -

    - name: "UI Tests - Chrome"
          uses: cypress-io/github-action@v2
          with:
            browser: "${{ github.event.inputs.browser }}"
            record: true
            parallel: true
            group: "UI - Chrome"
            spec: "${{ github.event.inputs.spec }}"
          env:
            CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

It was able to get the value without the quotes as it is with the quotes. I don't know what difference it made but it worked!

**Comment by robertguss** [comment]
@gonazmul glad you figured it out and got things working.
