### ISSUE TITLE
when installing - getting: error /User/myUser/node_modules/puppeteer: Command failed

### ISSUE THREAD

**Issue by shootermv** [cypress-io/cypress-realworld-app#1207]
OS:  Mac, M1
node: 16.13.2
![Screen Shot 2022-03-03 at 9 35 56](https://user-images.githubusercontent.com/1336862/156519173-237debbf-9f12-432b-a100-07b0df4c27c9.png)

**Comment by allexiusw** [comment]
Any solution for this issue? I'm getting the same bug in Apple M2 Max.  `v16.20.1`.

**Comment by MikeMcC399** [comment]
@allexiusw 

https://github.com/cypress-io/cypress-realworld-app#mac-m1-chip-users-will-need-to-prepend-puppeteer_skip_chromium_downloadtrue says:

#### Mac M1 chip users will need to prepend `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`.

```shell
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn install
```

Perhaps this applies to M2 as well?

**Comment by allexiusw** [comment]
@MikeMcC399 it works also in M2, thanks for pointing it out.
