### ISSUE TITLE
Component Testing will make Percy always build fail.

### ISSUE THREAD

**Issue by hereiscasio** [cypress-io/cypress-realworld-app#1224]
I can't see this repo using any component testing with Percy.

But you can test it, 
it seems the current version of _**Cypress**_ has this bug.

Also, Is it possible that you can add some examples of component testing with _**Percy**_ in this repo as well?

**Comment by robertguss** [comment]
@hereiscasio We will be updating this repo with component tests when Cypress 10 is released, which is very soon. So stay tuned!

**Comment by hereiscasio** [comment]
TL;DR -> This issue reported is not correct.

sorry about that, because I finally found the problem.
The culprit is basically mixing Yarn and NPM in the project, 
and it finally has some weird issues that causing me simply can't figure out the root cause of the bug I just reported.

anyway, thx for the info.
