### ISSUE TITLE
$ husky install fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by TLKG** [cypress-io/cypress-realworld-app#1243]
Towards the end of `yarn install`, received the message, no other error/warning.

I then was able to `yarn dev` to start the app, it took about a minute to finally see the login screen. New to Cypress. Using VSC in Windows, has local git and connects to GitHub. Can I ignore this msg?

```
Version: 1.63.1 (system setup)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:54.292Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by robertguss** [comment]
@TLKG how did you download the Real World App onto your machine? Did you download the zip file? It seems like when you downloaded the version onto your computer you did not get the `.git` directory.

Also you probably want to install git on your machine if you don't already. This is my preferred way on Windows: https://git-scm.com/downloads
