### ISSUE TITLE
issue with yarn dev

### ISSUE THREAD

**Issue by weilin-ong** [cypress-io/cypress-realworld-app#1245]
I'm getting the attached error, could you help please?

![Screenshot 2022-05-24 at 21 36 15](https://user-images.githubusercontent.com/73017624/170048648-66831574-35b5-4091-9611-4d8a9718a611.png)

**Comment by robertguss** [comment]
@weilin93 it looks like you are using Node 17.4.0 please use any version of Node 16.

**Comment by robertguss** [comment]
Please let me know if this solves your issue, or if you are still having problems. Thanks.

**Comment by weilin-ong** [comment]
it works now, thanks!!

**Comment by haibgit** [comment]
the same issue, my computer installed node v18, I need to remove and re-install node V16.
it works for me!
