### ISSUE TITLE
Testing the app on the network doesn't work

### ISSUE THREAD

**Issue by hamza-amami** [cypress-io/cypress-realworld-app#1246]
Because I don't have access to my localhost (protected by cisco), I go to the plateform via network : ipadress:3000
The front work well, but when I try to connect I get an error, it tries to call localshot:3001

Is there a way to deploy also the backend in ipadress:3001 please ?

**Comment by robertguss** [comment]
@hamza-amami I am not sure if I understand your issue entirely, but you can configure which ports both the frontend and backend run on in the `.env` file

https://github.com/cypress-io/cypress-realworld-app/blob/develop/.env#L14=
