### ISSUE TITLE
Update MUI dependencies

### ISSUE THREAD

**Issue by caseycling** [cypress-io/cypress-realworld-app#1278]
The app currently throws warnings that several MUI dependencies are now depreciated

**Comment by caseycling** [comment]
I have updated the dependencies and resolved the warnings. Can I make a PR for this issue?

**Comment by AtofStryker** [comment]
@caseycling is this an upgrade to version 5? I am noticing some failures in the notifications spec in FF that seem to be related to firefox specifically and material UI 4
![](https://user-images.githubusercontent.com/3980464/225661527-b8a2f938-b85c-4716-8f50-1cd76bacd11b.png). I am going to link this issue in the repo to try unskipping this test once we upgrade to v5

**Comment by nagash77** [comment]
Unfortunately we need to close this issue due to inactivity.  If you have relevant updates please comment here and we can reopen the issue for investigation.

**Comment by timheilman** [comment]
After upgrading to MUI v5 (https://github.com/cypress-io/cypress-realworld-app/pull/1522) indeed this test is passing in firefox.  Re-enabled test in https://github.com/cypress-io/cypress-realworld-app/pull/1522/commits/3a202702b3ab254547bc0e9d0f49aeb530a1db29
