### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by dhorkin** [cypress-io/cypress-realworld-app#1284]
looks like dependencies need to be updated in package.json.

Things appear to work with `npm i --force`, but ideally, a sample app shouldn't require that.
>╰─ npm i                                                                                                                          ─╯
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress-realworld-app@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-infinite-calendar@2.3.1
npm ERR! node_modules/react-infinite-calendar
npm ERR!   react-infinite-calendar@"2.3.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ingoCollatz** [comment]
> Note: The Cypress Real World App uses [Yarn](https://yarnpkg.com/) to manage its dependencies. Please install [Yarn](https://yarnpkg.com/) on your computer as installing with npm may lead to issues running the application.

https://learn.cypress.io/real-world-examples/cypress-real-world-app-overview

**Comment by nagash77** [comment]
Hi @FFdhorkin , as @ingoCollatz pointed out please use yarn while working with the realworld app.  Note make sure you are using the latest version of Yarn 1 (and not Yarn 3 which I have seen problems with)
