### ISSUE TITLE
[Question] How to run tests in parallel?

### ISSUE THREAD

**Issue by AObzh** [cypress-io/cypress-realworld-app#1289]
How to safely run cypress tests in parallel mode if most of them change db state before each test (`cy.task("db:seed");`, `  cy.task("db:clean");` etc.)?

**Comment by JeevanPurushotham** [comment]
https://docs.cypress.io/guides/guides/parallelization#What-you-ll-learn

**Comment by nagash77** [comment]
@AObzh Github issues are reserved for bugs and feature requests.  For all questions please check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
