### ISSUE TITLE
Authorisation doesn't work if device is remote (Not localhost)

### ISSUE THREAD

**Issue by Imolos** [cypress-io/cypress-realworld-app#1302]
I can't login into RWA with already created users. I always get "Incorrect username or password" 

And this problem only occurs when I try it on Virtual machines to which I connect by [IP Address]:3000

When I try it directly on host (M1 Mac) authetification starts working. And when I try to connect to the Mac by other device I again get "Incorrect username or password"

**Comment by nagash77** [comment]
Hi @Imolos , can you please provide a link to a reproducible example of what you are seeing with reproduction steps?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
