### ISSUE TITLE
Unmaintained GitLab mirror

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1325]
There exists an out-of-date mirror of this repository on GitLab

- https://gitlab.com/cypress-io/cypress-realworld-app

The last commit is 7f37dd7ca721b3c29e41cdfb775ad49a2063e01e from Dec 9, 2022.

- In https://github.com/cypress-io/cypress-example-kitchensink/issues/615 it was decided to archive the related GitLab repository

    - https://gitlab.com/cypress-io/cypress-example-kitchensink

I suggest that it should also be considered to archive the mirror of `cypress-realworld-app`.

**Comment by mjhenkes** [comment]
We'll get those archived

**Comment by MikeMcC399** [comment]
https://gitlab.com/cypress-io/cypress-realworld-app is archived.
