### ISSUE TITLE
Non-working links to CI provider examples for Cypress Cloud

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1330]
- https://github.com/cypress-io/cypress-documentation/issues/5149 logs issues on [CI Provider Examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples) which refer to recording from this repository

    [cypress-io/cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app/)

    to

    [Cypress Cloud](https://cloud.cypress.io/).

I cannot debug this issue because it requires access to secrets or access to Cypress.io-owned accounts on the respective CI provider.

Only the CircleCI project ID is working. The others are not.

CI provider | Project ID | Viewable
--- | --- | ---
CircleCI | [7s5okt](https://dashboard.cypress.io/projects/7s5okt) | yes
GitHub Actions | [tpys4j](https://dashboard.cypress.io/projects/tpys4j) | no
BitBucket | [q1ovwz](https://dashboard.cypress.io/projects/q1ovwz) | no
GitLab CI | [woih1m](https://dashboard.cypress.io/projects/woih1m) | no
AWS CodeBuild | [zx15dm](https://dashboard.cypress.io/projects/zx15dm) | no

**Comment by MikeMcC399** [comment]
At least in the case of the Bitbucket link https://dashboard.cypress.io/projects/q1ovwz the problem is not the link, but the visibility i.e. access rights of external readers to the Cypress Cloud project.

[.github/workflows/sync-bitbucket.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/sync-bitbucket.yml) gives a clue to the location 

https://bitbucket.org/cypress-io/cypress-realworld-app

https://bitbucket.org/cypress-io/cypress-realworld-app/pipelines/results/375 shows

![image](https://user-images.githubusercontent.com/66998419/233050998-231bf5b7-8a11-4f3f-8b2b-dee32f9f34f3.png)

https://bitbucket.org/cypress-io/cypress-realworld-app/pipelines/results/374/steps/%7B4f6fed9c-f54a-45c4-91a1-38397f82935b%7D however shows

  Recorded Run: https://cloud.cypress.io/projects/q1ovwz/runs/276 

and the contents on this URL is not accessible externally. So apart from the quota issue, it's an access issue for the results of the Atlassian Bitbucket CI on Cypress Cloud.

**Comment by chrisbreiding** [comment]
I addressed this here: https://github.com/cypress-io/cypress-documentation/issues/5149#issuecomment-1544030316

**Comment by MikeMcC399** [comment]
Most issues are resolved with the exception of GitLab which was disabled.
