### ISSUE TITLE
Google credentials are not included in .env file

### ISSUE THREAD

**Issue by TrentonPrattRTS** [cypress-io/cypress-realworld-app#1333]
I am unable to see a working example of testing with Google authentication. I suspect it's because there are no Google credentials to uncomment in the .env file. Auth0, Okta, and AWS credentials are supplied as expected

**Comment by nagash77** [comment]
Hi @TrentonPrattRTS can you provide more detail about what you are doing and share a reproducible example for us to investigate?

Programmatically logging into Google should work.  If you have general questions about using Cypress check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by TrentonPrattRTS** [comment]
Hello, yes I just wanted to see a working example of google authentication. The loginByGoogleApi function uses googleClientId, googleClientSecret, and googleRefreshToken variables that are all supposedly in the .env file but currently are not. I'm not sure if I'm just missing something but the other authorization credentials are in the .env file so it definitely seems like the google ones should be as well

**Comment by AtofStryker** [comment]
Hi @TrentonPrattRTS . I'm taking a look now and indeed the variables are missing. I'm going to see if I can get the example working and get a PR open for the updates needed. It looks like the needed variables are referenced in the [cypress config](https://github.com/cypress-io/cypress-realworld-app/blob/renovate/cypress-3.x/cypress.config.js#L52) and are:

```
GOOGLE_REFRESH_TOKEN=
REACT_APP_GOOGLE_CLIENTID=
REACT_APP_GOOGLE_CLIENT_SECRET=
````
