### ISSUE TITLE
Workflow merge-develop-into-flake-demo fails

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1340]
[.github/workflows/merge-develop-into-flake-demo.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/merge-develop-into-flake-demo.yml) fails.

It was last successful on Feb 25, 2023.

An example of a failing job is https://github.com/cypress-io/cypress-realworld-app/actions/runs/4767665114

The error is

```text
TypeError: Cannot read properties of undefined (reading 'create')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:3:33)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15144:12)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'create')
```

**Comment by MikeMcC399** [comment]
There is a secondary issue which will cause the workflow to fail in a few weeks:

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

"We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error."

**Comment by MikeMcC399** [comment]
You might like to consider simply deleting the workflow [.github/workflows/merge-develop-into-flake-demo.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/merge-develop-into-flake-demo.yml) and associated branch [flake-demo](https://github.com/cypress-io/cypress-realworld-app/tree/flake-demo).

- [flake-demo](https://github.com/cypress-io/cypress-realworld-app/tree/flake-demo) is undocumented
- There are sufficient real flaky tests available anyway!
- The [flake-demo](https://github.com/cypress-io/cypress-realworld-app/tree/flake-demo) branch is quite untidy. (This branch is 292 commits ahead, 21 commits behind develop.)
- The workflow is failing and contains deprecated instructions
- It is currently leaving multiple orphaned branches such as [1d0c850-develop-into-flake-demo](https://github.com/cypress-io/cypress-realworld-app/tree/1d0c850-develop-into-flake-demo) behind

**Comment by MikeMcC399** [comment]
If the branch [flake-demo](https://github.com/cypress-io/cypress-realworld-app/tree/flake-demo) is to be retained, then the conflicts caused by attempting to merge the default branch into this branch need to be manually resolved.

The branch is fed by the permanently open draft PR https://github.com/cypress-io/cypress-realworld-app/pull/875.

**Comment by mschile** [comment]
There is an internal team that is considering using the branch so I am going to leave it for now. I resolved the merge conflicts and opened https://github.com/cypress-io/cypress-realworld-app/pull/1343 to fix the `set-output` deprecation.

**Comment by MikeMcC399** [comment]
Hi @mschile 

Thank you for addressing these issues!

This problem has left a number of orphaned branches behind and it would be good to clean these up:

```
$ git branch -r | grep develop-into-flake-demo
  upstream/179bde1-develop-into-flake-demo
  upstream/1d0c850-develop-into-flake-demo
  upstream/2810ba0-develop-into-flake-demo
  upstream/29c9cde-develop-into-flake-demo
  upstream/2a578a7-develop-into-flake-demo
  upstream/3792a9a-develop-into-flake-demo
  upstream/41d36f4-develop-into-flake-demo
  upstream/5030986-develop-into-flake-demo
  upstream/72247de-develop-into-flake-demo
  upstream/79c6227-develop-into-flake-demo
  upstream/7be1856-develop-into-flake-demo
  upstream/84bd778-develop-into-flake-demo
  upstream/d149ee6-develop-into-flake-demo
  upstream/e84356f-develop-into-flake-demo
  upstream/edf3753-develop-into-flake-demo
```

Please let me know if I should submit a separate issue for this. I can't do the clean-up myself since I don't have write access to the repo.

**Comment by mschile** [comment]
@MikeMcC399, I cleaned up the orphaned branches.

**Comment by MikeMcC399** [comment]
@mschile 
>  I cleaned up the orphaned branches.

Perfect!

I checked and the workflow is also succeeding
https://github.com/cypress-io/cypress-realworld-app/actions/runs/4871651055

(I was confused about a failing workflow from [matth/test-video-performance](https://github.com/cypress-io/cypress-realworld-app/tree/matth/test-video-performance) which I happened to notice. That branch is a long way behind current status. Just thought I'd mention it, even though it is totally unrelated to this PR! 🙂 )
