### ISSUE TITLE
build warning from @babel/plugin-proposal-private-property-in-object

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1363]
When executing

```bash
yarn build
```

the following warning is issued:

>One of your dependencies, babel-preset-react-app, is importing the
>"@babel/plugin-proposal-private-property-in-object" package without
>declaring it in its dependencies. This is currently working because
>"@babel/plugin-proposal-private-property-in-object" is already in your
>node_modules folder for unrelated reasons, but it may break at any time.
>
>babel-preset-react-app is part of the create-react-app project, which
>is not maintianed anymore. It is thus unlikely that this bug will ever
>be fixed. If you are starting a new project, you may consider using
>maintained alternatives such as Vite (https://vitejs.dev/) instead.
>
>Add "@babel/plugin-proposal-private-property-in-object" to your
>devDependencies to work around this error. This will make this message
>go away.

## Expectation

No warning about incorrect dependencies should be displayed when building the app.

## Steps to reproduce

On Ubuntu 22.04 with Node.js `16.16.0`
In a clone of https://github.com/cypress-io/cypress-realworld-app or fork of this repo, execute

```bash
npm install yarn@latest -g
rm -rf node_modules
yarn
yarn dev
```

See also job [9504002434](https://github.com/cypress-io/cypress-realworld-app/actions/runs/5259014738/jobs/9504002434) > `Run yarn build:ci`

## Other

The warning message was introduced on June 6, 2023 into https://github.com/babel/babel-plugin-proposal-private-property-in-object

[babel-preset-react-app@10.0.1](https://www.npmjs.com/package/babel-preset-react-app) is a dependency of [react-scripts@4.0.3](https://www.npmjs.com/package/react-scripts), which is unmaintained according to the build message.

**Comment by MikeMcC399** [comment]
According to @elylucas, RWA is being reworked, so I suggest to put this issue on hold as it does not affect the operation of RWA.

**Comment by mschile** [comment]
Thanks @MikeMcC399, confirmed the build output shows the new warning.
