### ISSUE TITLE
Bitbucket mirror not synced - ssh host key changed

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1369]
The [Sync Bitbucket over SSH](https://github.com/cypress-io/cypress-realworld-app/actions/workflows/sync-bitbucket.yml) workflow has stopped working. The last successful sync was on June 15, 2023.

The sync is from 
https://github.com/cypress-io/cypress-realworld-app to 
https://bitbucket.org/cypress-io/cypress-realworld-app.

```
Pushing to bitbucket.org:cypress-io/cypress-realworld-app
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:46OSHA1Rmj8E8ERTC6xkNcmGOw9oFxYr0WF6zWW8l1E.
Please contact your system administrator.
Add correct host key in /home/runner/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/runner/.ssh/known_hosts:3
  remove with:
  ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "bitbucket.org"
Host key for bitbucket.org has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Process completed with exit code 128.
```

[Cypress Cloud](https://cloud.cypress.io/projects/q1ovwz/runs) shows the last CI run with Bitbucket on June 1, 2023.

## Suggestion

Read https://bitbucket.org/blog/ssh-host-key-changes and implement ssh host key changes.

**Comment by MikeMcC399** [comment]
- https://github.com/cypress-io/cypress-documentation/pull/5360

indicates that the Bitbucket pipelines will not be maintained, so this issue is obsolete.

**Comment by jennifer-shehane** [comment]
Closing, bitbucket mirror has been removed. @MikeMcC399 If you'd like you could remove the bitbucket-pipeline file in a PR.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Closing, bitbucket mirror has been removed. @MikeMcC399 If you'd like you could remove the bitbucket-pipeline file in a PR.

- I already submitted PR https://github.com/cypress-io/cypress-realworld-app/pull/1376 to close this issue, so now the issue is closed before the PR which would resolve it, but never mind! Leave the issue closed.
