### ISSUE TITLE
Bitbucket pipelines failing

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1370]
[Bitbucket pipelines](https://bitbucket.org/cypress-io/cypress-realworld-app/pipelines) are either
- failing 

![Image](https://github.com/cypress-io/cypress-realworld-app/assets/66998419/737adb83-4389-4ba1-95fb-71222e87a54c)

- paused due to lack of quota 

![Image](https://github.com/cypress-io/cypress-realworld-app/assets/66998419/4124b3c8-82c0-476e-8b19-0bd2985cffb1)

**Comment by nagash77** [comment]
Hi @MikeMcC399 this is something we are no longer supporting.  @jennifer-shehane [opened a PR](https://github.com/cypress-io/cypress-documentation/pull/5360) to remove the links to this to clear up any confusion.

I'll go ahead and close this issue at this time.

**Comment by MikeMcC399** [comment]
Hi @nagash77 

In that case the workflow
https://github.com/cypress-io/cypress-realworld-app/blob/develop/bitbucket-pipelines.yml

should be deleted. Will @jennifer-shehane do that or should I submit a PR?

**Comment by nagash77** [comment]
Hi @MikeMcC399 if you could open a PR that would be appreciated.

**Comment by MikeMcC399** [comment]
@nagash77 

>  if you could open a PR that would be appreciated.

- See https://github.com/cypress-io/cypress-realworld-app/pull/1376
