### ISSUE TITLE
Suggest to delete stale branches

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1371]
[Stale branches](https://github.com/cypress-io/cypress-realworld-app/branches/stale) in this repo should be deleted, especially

- [main](https://github.com/cypress-io/cypress-realworld-app/tree/main) which can be (and was) mistaken for an active branch.

**Comment by allexiusw** [comment]
https://hackernoon.com/clean-stale-branches-with-github-actions Do you agree to setup a solution like that? I can work in that 👨‍💻 basically is setup a GitHub action to do it automatically. We can customize the frequency of the task to run, daily, weekly, monthly, etc and the threshold to filter the branches to be removed.

**Comment by MikeMcC399** [comment]
@allexiusw 

> Do you agree to setup a solution like that?

This would not be my decision as I am a Contributor, not a member of Cypress.io. I would be happy for a simple manual clean-up.

I would be wary of a destructive automated process relying on an external JavaScript Action. There is no inherent recycle bin to recover from errors.

**Comment by astone123** [comment]
Deleted all stale branches - I think I agree that I'd rather not have an automatic cleanup of stale branches
