### ISSUE TITLE
what are the concepts are should learn to become a good cypress automation engineer?

### ISSUE THREAD

**Issue by santhanamKheshu** [cypress-io/cypress-realworld-app#1378]
Hi,
I am new to automate test. I first step into cypress automation and don't have any knowledge of what and all should learn to become a cypress tester. Please give me a list of guidelines so i will follow-up and crack the interviews.

It's also good to provide me a „ JavaScript Tutorial " chapters for the cypress.

**Comment by MikeMcC399** [comment]
Hello @santhanamKheshu 

You can ask your peers in the Cypress technical community on Discord for their recommendations. You should be looking a taking training, however you shouldn't expect any more specific answer here in this repository as the issue list is for reporting problems with the demo Real World App, not for getting career guidance.

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)

**Comment by santhanamKheshu** [comment]
Please share me the link of the Cypress technical community to post my queries.

**Comment by MikeMcC399** [comment]
@santhanamKheshu 

Just click on the button [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) which will take you to https://on.cypress.io/discord

**Comment by santhanamKheshu** [comment]
Thank you

**Comment by nagash77** [comment]
Issues are reserved for bugs and feature requests.  I will be closing this issue at this time..  Please check out the Cypress Discord Community Discord chat, it can be helpful for debugging or answering questions on how to use Cypress.
