### ISSUE TITLE
Cancel button should be disappear when user in " https://cloud.cypress.io/login " page

### ISSUE THREAD

**Issue by sait-yamdu** [cypress-io/cypress-realworld-app#1411]
This irrites me when I was checking cypress prices. Please remove the cancel button when the user does not select Log in with email or Log in with SSO options in the screenshot. Thank you.

![image](https://github.com/cypress-io/cypress-realworld-app/assets/143401052/141b193b-0da2-49b9-8176-6997a267a5f4)

**Comment by astone123** [comment]
@sait-yamdu thank you for your issue. Our Cloud team has been informed about this. This repository is for our Real World test app, not Cypress Cloud, so I'm going to close this issue
