### ISSUE TITLE
Migrate away from express-graphql package

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress-realworld-app#1420]
The [`express-graphql`](https://www.npmjs.com/package/express-graphql) package is deprecated and does not support the version of GraphQL that we're on. We should move off of it to a different GraphQL server package that still allows us to easily standup GraphiQL. Possible candidates

- [Apollo Server](https://www.apollographql.com/docs/apollo-server)?
- [GraphQL Yoga](https://the-guild.dev/graphql/yoga-server)?

**Comment by hiepluong2205** [comment]
+1 for Apollo Server

**Comment by timheilman** [comment]
I believe this was resolved by https://github.com/cypress-io/cypress-realworld-app/pull/1521 using graphql-http and graphql-playground
