### ISSUE TITLE
Add .gitlab-ci.yml

### ISSUE THREAD

**Issue by wscourge** [cypress-io/cypress-realworld-app#1427]
It'd be real useful to have a working [Gitlab CI](https://docs.cypress.io/guides/continuous-integration/gitlab-ci) configuration available in this repository as _.gitlab-ci.yml_ file.

It could be done with multiple git origins added:

```
git remote add origin git@gitlab.com:cypress-io/cypress-realworld-app.git
git remote set-url --add --push origin git@gitlab.com:cypress-io/cypress-realworld-app.git
```

With those in place, a single `git push` would be propagated to both Github (current) and Gitlab (I made some assumptions about naming, same as Github).

**Comment by MikeMcC399** [comment]
@wscourge 

There used to be a working GitLab mirror, however the Cypress team decided not to support this anymore and it was disabled. 

The mirror at https://gitlab.com/cypress-io/cypress-realworld-app is archived.

- See https://github.com/cypress-io/cypress-realworld-app/issues/1325

GitLab as CI is documented on https://docs.cypress.io/guides/continuous-integration/gitlab-ci. These are however documentation-only examples with no running versions of them available.

**Comment by wscourge** [comment]
Thanks, I was not aware of this.

I don't see any reasoning behind the decision. My proposition is that you link this issue in the docs you mentioned, and if others upvote it in a reasonable time, consider supporting it again.

I don't mind either way, feel free to close this issue. Thanks for your quick response and helpful links, and keep up the good work.
