### ISSUE TITLE
Running yarn prettier doesn't work

### ISSUE THREAD

**Issue by Masa-99** [cypress-io/cypress-realworld-app#1454]
Hey everyone!

When running `yarn prettier`, I get this error:
![image](https://github.com/cypress-io/cypress-realworld-app/assets/44638953/a12c054c-8702-4b09-8894-beb2dfe62f7d)

This can be fixed, when fixing this in line 174 of the `package.json`:
`"prettier": "prettier --write '**/**.{ts,js,tsx}' '*.{json,md,yml}'",`
With this (oriented on line 156 which throws no errors and is checking for errors):
`"prettier": "prettier --write \"**/**.{ts,js,tsx}\" \"*.{json,md,yml}\"",`

I can create a pull request for this if needed :)

**Comment by MikeMcC399** [comment]
@Masa-99 

Good catch! It seems that `yarn prettier` isn't used anywhere, so it wasn't noticed that the script doesn't work

The `yarn lint` script already has the fix you suggest and this works correctly:

```json
   "lint": "eslint && prettier --check \"**/**.{ts,js,tsx}\" \"*.{json,md,yml}\"",
```

```text
$ yarn lint
yarn run v1.22.19
$ eslint && prettier --check "**/**.{ts,js,tsx}" "*.{json,md,yml}"
Checking formatting...
All matched files use Prettier code style!
Done in 2.94s.
```

You can wait for feedback from the Cypress.io team, however I think it would make sense to submit a PR making the change you suggested.

---

As a separate topic, the version of [prettier](https://www.npmjs.com/package/prettier) used in this repo is `prettier@3.0.0`, whereas the current version is [3.2.4](https://github.com/prettier/prettier/releases/tag/3.2.4).
