### ISSUE TITLE
main workflow broken - upload- / download-artifacts using different versions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1509]
## Issue

[Workflow logs for main.yml](https://github.com/cypress-io/cypress-realworld-app/actions/workflows/main.yml) shows only the `install` is succeeding, all other jobs fail with the error

> Unable to find any artifacts for the associated workflow

- This problem was introduced through merging https://github.com/cypress-io/cypress-realworld-app/pull/1487

The `install` job uploads artifacts using [actions/upload-artifact@v4](https://github.com/actions/upload-artifact/releases/tag/v4.0.0) which is incompatible with `actions/download-artifact@v3`. See release notes [actions/download-artifact@v4](https://github.com/actions/download-artifact/releases/tag/v4.0.0)
> Uploads and downloads must use the same major actions versions.

## Resolution

- [actions/download-artifact](https://github.com/actions/download-artifact) must be updated to `@v4`, for instance through PR https://github.com/cypress-io/cypress-realworld-app/pull/1485

**Comment by jennifer-shehane** [comment]
Closed in https://github.com/cypress-io/cypress-realworld-app/pull/1485
