### ISSUE TITLE
AWS Amplify Deployment

### ISSUE THREAD

**Issue by DavidTNguyen** [cypress-io/cypress-realworld-app#1546]
I forked the repo and tried to deploy the app on AWS Amplify, but run into some issue with tried to connect to the repo.  Does anyone experience the same behavior when working with AWS?

```
YAMLException: the stream contains non-printable characters at line 51, column 32: name: Build CI â¹ï¸ ^
```
![deployment](https://github.com/cypress-io/cypress-realworld-app/assets/11265859/9231a158-5a74-41d9-860d-2a28885a3c0f)

**Comment by MikeMcC399** [comment]
@DavidTNguyen 

Your error message refers to Line 51 `name: Build CI`
That could correspond to 

https://github.com/cypress-io/cypress-realworld-app/blob/1b451caf8d096827cd8f052b5b420ee207196057/.circleci/config.yml#L51

which does indeed contain a character ℹ️. This is in a workflow for CircleCI and it may not be useful or needed in your configuration.

Perhaps other log files would confirm whether it is actually this file which is causing the error?

You could remove the problematic character ℹ️, or perhaps disable / delete the file with the ℹ️ character.

**Comment by DavidTNguyen** [comment]
That's it. Thank you. I wish Amplify Console provided the file where that caused the problem.  It'd been a lot more developer friendly.
