### ISSUE TITLE
Error install 

### ISSUE THREAD

**Issue by fauzisunarya** [cypress-io/cypress-realworld-app#1559]
hello, I experienced an error when I wanted to run the yarn dev syntax, the error is like the following picture, what is the solution, thank you

![image](https://github.com/cypress-io/cypress-realworld-app/assets/43233727/ca81703f-1932-4cf0-bf9c-3a42cc4d60bc)

**Comment by MikeMcC399** [comment]
@fauzisunarya 

Have you modified this example? I don't see any `postcss-safe-parser` installed using the original example from https://github.com/cypress-io/cypress-realworld-app

**Comment by fauzisunarya** [comment]
I downloaded the source code manually from here:
https://github.com/cypress-io/cypress-realworld-app/releases/tag/v1.0.18

After I downloaded it, I followed it step by step and the error appeared

**Comment by MikeMcC399** [comment]
@fauzisunarya 

Thanks for explaining! https://github.com/cypress-io/cypress-realworld-app/releases/tag/v1.0.18 is an old version from the year 2021. You shouldn't be using this. Unfortunately the README is not clear about this.

Delete your v1.0.18 and replace it with

```shell
git clone https://github.com/cypress-io/cypress-realworld-app
```

**Comment by fauzisunarya** [comment]
thank you, it worked

Can this script be uploaded to the server so I don't need to run it locally anymore?

**Comment by MikeMcC399** [comment]
@fauzisunarya 
> thank you, it worked

That's good! I'll submit a request for document change so the instructions are improved.

> Can this script be uploaded to the server so I don't need to run it locally anymore?

I don't understand what you are asking for here. Please explain which script you mean. If you want to run anything on a GitHub server, then you need to clone the repo.

**Comment by fauzisunarya** [comment]
I want to run it on my own server, not the GitHub server, is that possible?

**Comment by MikeMcC399** [comment]
@fauzisunarya 

> I want to run it on my own server, not the GitHub server, is that possible?

You should be able to run the code on your server. For "how-to" type questions there is an active Cypress user community on Discord [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button) that you might like to join.

**Comment by MikeMcC399** [comment]
Related issues / PRs to improve user experience:
- https://github.com/cypress-io/cypress-realworld-app/issues/1560
- https://github.com/cypress-io/cypress-realworld-app/pull/1561
- https://github.com/cypress-io/cypress-realworld-app/pull/1562

**Comment by MikeMcC399** [comment]
@fauzisunarya 

You should be able to close this issue now. See button below ⬇️

**Comment by fauzisunarya** [comment]
Thank's
