### ISSUE TITLE
Remove display of outdated releases or publish new release

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1560]
## Issue

The latest release of this repo, shown under https://github.com/cypress-io/cypress-realworld-app/releases, is [v1.0.18](https://github.com/cypress-io/cypress-realworld-app/releases/tag/v1.0.18) from Aug 7, 2021. This is already 3 years ago.

## Suggestion

Either

- remove Releases from display in the About section of https://github.com/cypress-io/cypress-realworld-app OR
- make a new release

This can only be handled by a user with write privileges to the repo. It can't be submitted as a PR.

**Comment by jennifer-shehane** [comment]
You'd have to delete all the releases to hide this? Or is there a way to just hide the link to Releases?

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Click on the About gear-wheel, unselect Releases

Screenshot from my fork where they are already unselected:

![image](https://github.com/cypress-io/cypress-realworld-app/assets/66998419/23a4ccfb-80e6-442f-b299-25b4d7a2bf88)

**Comment by jennifer-shehane** [comment]
Oooo, I did not know that existed. I removed the releases.
