### ISSUE TITLE
Awaiting XState service initialization by initialized property does not work

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-realworld-app#334]
## Problem
We need to wait for XState services to be initialized before we can utilize them within test commands. For example, we utilize the `cy.loginByXstate()` custom command to programmatically login a user.

To await XState services, the custom command `cy.waitForXstateService` has been implemented like so:

```js
Cypress.Commands.add("waitForXstateService", (service) => {
  return cy.window({ log: false }).should((win) => {
    if (!win[service].initialized) {
      throw new Error(`${service} is not ready!`);
    }
  });
});
```

However the `initialized` property of XState services does not seem to be a reliable indicator that the service is ready for use, or the current implementation of this command is insufficient.

The undesirable and temporary fix for giving XState services to be initialized has been to introduce a 100ms wait. Disabling this small wait period causes failures across various spec files, which can be seen in this run within the Cypress Dashboard: https://dashboard.cypress.io/projects/7s5okt/runs/1180/failures

## Objective
Identify and implement a reliable indicator and method for awaiting full initialization/readiness of XState services.

**Comment by davidkpiano** [comment]
@amirrustam If the purpose of this is to test implementation details (rather than a normal E2E test that doesn't assume XState is being used), you can take advantage of hooking into the dev tools for XState to know when a service comes into existence and is registered. 

Here is a barebones implementation:

```js
const startedServices = new Map();

window.__xstate__ = {
  register: (service) => {
    console.log('registered service!', service.machine.id);
  }
}

// Services must opt-in to dev tools
const someService = interpret(someMachine, {
  devTools: true
});
```

Are the services starting immediately?

**Comment by amirrustam** [comment]
@davidkpiano thanks for stepping in here and providing your feedback. We appreciate it.

> Are the services starting immediately?

Yes, the services are starting immediately, but this issue actually ended up being a red-herring. @kevinold did some great debugging and identified that issue was with our `authMachine` getting stuck in a particular state.

For our own curiosity, what is the reason for `__xstate__.register()` being prefered over `service.initialized`?

@all-contributors please add @davidkpiano for ideas.
