### ISSUE TITLE
Demonstrate Visual Testing

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-realworld-app#366]
## Objective
Demonstrate visual testing setup with one of the following methods:
- [Percy Cypress plugin](https://github.com/percy/percy-cypress)
- [Applitools Eyes Cypress Plugin](https://github.com/applitools/eyes.sdk.javascript1/tree/master/packages/eyes-cypress)
- [cypress-image-snapshot](https://github.com/palmerhq/cypress-image-snapshot)

**Comment by kevinold** [comment]
Fixed in #514
