### ISSUE TITLE
XState 4.10 Upgrade causing Unhandled Rejection Error 

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-realworld-app#370]
## Problem
XState upgarde to v4.10 causes the following Unhandled Rejection error.
- Reproduction: https://github.com/cypress-io/cypress-realworld-app/pull/369
- Failure:https://dashboard.cypress.io/projects/7s5okt/runs/1281/failures/1cfef65a-e0bc-4264-8d4b-f4cde8e741c0

**Comment by davidkpiano** [comment]
Looking into this. If possible, when you determine the root cause, can you post the issue in XState?
