### ISSUE TITLE
Flaky notifications test for like in Firefox Mobile Viewport

### ISSUE THREAD

**Issue by kevinold** [cypress-io/cypress-realworld-app#403]
## Problem

When validating notifications from user interactions, "User A likes a transaction of User B; User B gets notification that User A liked transaction" in `notifications.spec.ts`, the assertion fails to match "liked" for the first notification item in the list.

The command log shows a cancellation of the POST to `/likes/{transactionId}` prior to logout via command (XState) in the Firefox mobile viewport scenario. 

![cypress-screenshot](https://user-images.githubusercontent.com/21967/84281682-7e8ff480-aafe-11ea-99d1-766549d21679.png)

- Reproduction within [Cypress Dashboard run 1414](https://dashboard.cypress.io/projects/7s5okt/runs/1414/failures/ba9590e5-1f68-4abe-8169-ab9ae059f632) 

## Objective
- Investigate root cause of like network request cancellization
- Update test and/or application code to remedy this scenario and confirm the resolution of flakiness via several back-to-back runs in CI.

**Comment by amirrustam** [comment]
No longer an issue

**Comment by kevinold** [comment]
Reopened due to flaky failure: https://dashboard.cypress.io/projects/7s5okt/runs/1432/failures/339244a9-2538-4bd9-862e-3266e66aa386

**Comment by kevinold** [comment]
Fixed in #421
