### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by m0t0r** [cypress-io/cypress-realworld-app#407]
Hello, 

Thanks a lot for this app! 

However, I am having issues running it locally. There are compilation errors about type mismatch

```shell
backend/user-routes.ts(36,66): error TS2345: Argument of type 'string | ParsedQs | string[] | ParsedQs[] | undefined' is not assignable to parameter of type 'string'.
[start:api:watch]   Type 'undefined' is not assignable to type 'string'.
```

```shell
/backend/transaction-routes.ts(43,7):
[start:react] Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'number'.
[start:react]   Type 'undefined' is not assignable to type 'number'.  TS2345
```

**Comment by amirrustam** [comment]
@m0t0r thanks for following up. Which branch did you clone?

**Comment by m0t0r** [comment]
@amirrustam develop

**Comment by m0t0r** [comment]
@amirrustam I can create a PR if that helps. Please let me know

**Comment by amirrustam** [comment]
Contributions are always welcome :)

**Comment by kevinold** [comment]
Thanks for reporting @m0t0r!

**Comment by amirrustam** [comment]
@m0t0r are you using npm or yarn?

**Comment by amirrustam** [comment]
@m0t0r  Did you use npm to install by any chance?

**Comment by m0t0r** [comment]
@amirrustam yes, I used `npm i`

**Comment by amirrustam** [comment]
Can you start fresh and use `yarn`, and then let us know if the issue persists? This issue is related to typing issues with `express` types.

**Comment by m0t0r** [comment]
@amirrustam with `yarn start` I am seeing these errors:

```shell
Failed to compile.
[start:react]
[start:react] ./src/svgs/rwa-logo.svg (./node_modules/@svgr/webpack/lib?-svgo,+titleProp,+ref!./src/svgs/rwa-logo.svg)
[start:react] Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
[start:react] Require stack:
[start:react] - /Users/m0t0r/WebProjects/cypress-realworld-app-fork/node_modules/@svgr/webpack/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
```

**Comment by amirrustam** [comment]
This seems to be due to node-version, which version of node are you using? Pull the latest in develop we've fixed to 12.16.

**Comment by amirrustam** [comment]
@m0t0r to fix this we're updating by pinning `@babel/core` and `@babel/preset-env`. This is a known issue in other projects as well.

**Comment by amirrustam** [comment]
@magnolia-triplett can we please connect with @m0t0r and send him some Cypress goodies. We appreciate you reporting these issues, it always helps.

**Comment by m0t0r** [comment]
Thank you @amirrustam Happy to help!

**Comment by magnolia-triplett** [comment]
Hey @m0t0r, thanks for your help! We'd love to send you some swag - [click here](cypress.io/surprise) for more info.

**Comment by m0t0r** [comment]
Hi @magnolia-triplett thank you but I am seeing 404 page :)

<img width="1680" alt="Screen Shot 2020-06-12 at 9 47 31 AM" src="https://user-images.githubusercontent.com/3257149/84515252-d4e16c80-ac91-11ea-86c0-ae94a30689e2.png">
