### ISSUE TITLE
Unable to run the app due to typescript compilation error 

### ISSUE THREAD

**Issue by venkata-qe** [cypress-io/cypress-realworld-app#419]
**Issue Description**
I am getting the compilation error exception and the app crashed  when I try to run the app using "yarn dev"

**Environment**

- macOS Catalina 10.15.5
- Node v12.18.0
- Yarn v1.22.4

**Steps to reproduce:**
1. Clone the repository https://github.com/cypress-io/cypress-realworld-app.git
2.  yarn install - successfully executed
3. yarn dev - failing with the following exception
```
sample-apps/cypress-realworld-app/backend/transaction-routes.ts
TypeScript error in /Users/venkatakoripalli/Documents/git/sample-apps/cypress-realworld-app/backend/transaction-routes.ts(43,7):
Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.  TS2345

    41 | 
    42 |     const { totalPages, data: paginatedItems } = getPaginatedItems(
  > 43 |       req.query.page,
       |       ^
    44 |       req.query.limit,
    45 |       transactions
    46 |     );
```

**Comment by kevinold** [comment]
@venkata-qe Hi, please verify you have the latest from the develop branch, https://github.com/cypress-io/cypress-realworld-app/commit/87c59c42130c44590cb5388154af0098e4b65455.

With the latest,  please remove node_modules and `yarn install`

**Comment by kevinold** [comment]
Related to #413

**Comment by venkata-qe** [comment]
> @venkata-qe Hi, please verify you have the latest from the develop branch, [87c59c4](https://github.com/cypress-io/cypress-realworld-app/commit/87c59c42130c44590cb5388154af0098e4b65455).
> 
> With the latest, please remove node_modules and `yarn install`

Sorry I was on one commit older than 87c59c4.
Now taken the latest commit and the app is working fine.
Thank you for the prompt response and closing the issue.
