### ISSUE TITLE
Challenges on setting up on Windows 10 | Support for NPM

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress-realworld-app#424]
**Unable to setup a real-world app on windows 10.**

**Environment:**
Node version: 12.16.3
Yarn version 1.17.3 & tried with the latest version (1.22.4)

What I did till now:

- Cloned repo.
- Run : npm install 
- Run : yarn dev (Did not work, so installed yarn 1.17.3)
- Run : yarn dev
- Got error 'cp is not recognized as internal command.

![image](https://user-images.githubusercontent.com/25897622/84559349-b59a1c00-ad31-11ea-800c-0993f43c56bd.png)

- Changed package.json scripts from cp to copy and again ran : yarn dev
- Got error:
_copy data/database-seed.json data/database.json
data\database-seed.json
The file cannot be copied onto itself.
        0 file(s) copied._

![image](https://user-images.githubusercontent.com/25897622/84559374-00b42f00-ad32-11ea-904b-869f5efc8894.png)

PS: Setting up real world app on windows has become a challenge for majority of the testers, its been discussed in multiple channels. No concreate solution yet.

It would be great if you could add NPM support to it.

Thanks!
Anand

**Comment by kevinold** [comment]
Related to #420 and forthcoming fix in #421

**Comment by kevinold** [comment]
Related to #420 and forthcoming fix in #421

**Comment by kevinold** [comment]
Resolved in #421
