### ISSUE TITLE
Got errors in Windows 10 when run yarn start

### ISSUE THREAD

**Issue by tangrongzhu** [cypress-io/cypress-realworld-app#426]
1. Run yarn install --all success.
2. Run yarn start or yarn dev got bellow errors, but app started at http://localhost:3000/ ,all users are not able to login.
![image](https://user-images.githubusercontent.com/9548494/84589300-217aa280-ae60-11ea-9f6c-3f06e0894233.png)
3. Run yarn cypress:open and run any test will got following error:
![image](https://user-images.githubusercontent.com/9548494/84589126-3b67b580-ae5f-11ea-846f-24eb5f3f9972.png)

**Comment by amirrustam** [comment]
Thanks for reporting this issue. The error you are seeing in Cypress is because the backend failed to start so the database seeding task can't be executed. 

What version of TypeScript are you running?

**Comment by kevinold** [comment]
@tangrongzhu Which branch are you running?  Please test the branch against this #421

**Comment by kevinold** [comment]
Resolved in #421
