### ISSUE TITLE
Cant access app from different machine than the server.

### ISSUE THREAD

**Issue by Julioevm** [cypress-io/cypress-realworld-app#477]
Hi,  great work with the app, its very handy.

I'm trying to host the app in a machine and test it from a different one, but even tho I can access the login screen, the login itself fails. The login request is being made to localhost:3001 instead of the server address:

![image](https://user-images.githubusercontent.com/38758281/88275278-63a7c700-ccdd-11ea-9105-0c9e85f9b903.png)

Did I miss something when I set it up or is this a bug?
AFAIK all I did to set it up was to clone it and npm run start.

Thanks!

**Comment by kevinold** [comment]
@Julioevm  This application is meant to be run and tested on the same machine for demonstration purposes only.  Testing from another machine may require additional networking configuration on your machine, of which we cannot advise.

In short, the test machine is trying to access "localhost" on it's machine, where both frontend and backend servers are located on the app machine.
