### ISSUE TITLE
This error occurred during the build time and cannot be dismissed.

### ISSUE THREAD

**Issue by vivekbwaj** [cypress-io/cypress-realworld-app#563]
Issue #1: It takes way too long to install the packages.
Issue #2: Once done, "yarn start" throws on localhost:port
Error Log:
------------------------------------
Failed to compile
./src/svgs/rwa-logo.svg (./node_modules/@svgr/webpack/lib?-svgo,+titleProp,+ref!./src/svgs/rwa-logo.svg)
TypeError: [BABEL] unknown: Cannot read property 'chrome' of undefined (While processing: "programmatic item")
    at Array.filter (<anonymous>)
    at Generator.next (<anonymous>)

**Comment by kevinold** [comment]
@vivekbwaj 

- Remove your `node_modules` directory
- Ensure you are running Node v12 per our prerequisites - https://github.com/cypress-io/cypress-realworld-app#prerequisites
- Ensure another application is not running on the same port
