### ISSUE TITLE
cy.loginByApi - Authentication Fails after Logging In Via API

### ISSUE THREAD

**Issue by CypressHarry** [cypress-io/cypress-realworld-app#564]
## Steps To Reproduce

- Run below code: 
```
describe('Auth Via API', function(){
    beforeEach( function() {
        cy.task("db:seed");
        const password = Cypress.env("defaultPassword");
        const authUser = {
            username:"Katharina_Bernier",
            password
        };
        return cy.loginByApi(authUser.username);
    })
    it('skip UI login',()=>{
       
        cy.visit('http://localhost:3000/')
        cy.get('span').contains('My Account').click()
    })
})
```

## Desired Behavior

Test navigates to home page and asserts on the span 'My Account'.

## Actual Behavior

On `cy.visit`, the test bounces to `/signin` page and test fails

**Comment by amirrustam** [comment]
`cy.loginByAPI` is for the API tests. To use it for the E2E tests use `cy.loginByXstate`. You can see examples of this in tall the specs under `cypress/tests/ui` directory.
