### ISSUE TITLE
Username is required error on 'signin' page

### ISSUE THREAD

**Issue by krishhna123** [cypress-io/cypress-realworld-app#581]
I am running `Real World App` on local and observe that it always shows error `Username is required` on the page when one clicks anywhere on the page.

Steps to reproduce:
1. Visit http://localhost:3000/signin
2. Click on blank area of the page

Expected Result: 
There should not be any error displayed

Actual Result:
We are getting `Username is required` error message for `Username` field

<img width="1188" alt="Screenshot 2020-10-04 at 6 35 01 PM" src="https://user-images.githubusercontent.com/16148945/95016403-6d9c5d80-0670-11eb-9e81-5db9d478efaa.png">

**Comment by kevinold** [comment]
This is proper behavior of the form once focused, then unfocused.
