### ISSUE TITLE
Example of `shadow()` or `includeShadowDom`?

### ISSUE THREAD

**Issue by talyh** [cypress-io/cypress-realworld-app#661]
I've been trying to get Cypress to find elements based on attributes that exist in my React structure, but are not passed down all the way to the DOM. I assume that's the intent of `shadow()` or `includeShadowDom`.
This hasn't been working though in my project though.
I couldn't find a shadow example in this repo, so I'm wondering if it'd be possible to add one to help illustrate the correct intent and usage of these.

Thanks!

**Comment by kevinold** [comment]
Hi @talyh,

Currently there are no examples in the RWA, but as we are able we will add them.

In the meantime, refer to the following resources:

https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__shadow-dom
https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__lit-element/cypress/integration/shadow-tests.ts
https://docs.cypress.io/api/commands/shadow.html
