### ISSUE TITLE
Migrating server and route to intercept results in failed tests

### ISSUE THREAD

**Issue by oppahansi** [cypress-io/cypress-realworld-app#700]
I was trying to migrate **`cy.server()`** and **`cy.route(...)`** to **`cy.intercept(...)`**, e.g.:
`bankaccounts.spec.ts`

```
cy.server();
cy.route("POST", "/bankAccounts").as("createBankAccount");
cy.route("DELETE", "/bankAccounts/*").as("deleteBankAccount");
cy.route("GET", "/notifications").as("getNotifications");
```

To

```
cy.intercept("POST", "/bankAccounts").as("createBankAccount");
cy.intercept("DELETE", "/bankAccounts/*").as("deleteBankAccount");
cy.intercept("GET", "/notifications").as("getNotifications");
```

Which resulted in failed tests where the url had a wildcard matching character:
https://i.imgur.com/ESdBGem.png

The same behaviour occurs in all migrated tests. Requests are not being registered.

Another example:
`new-transaction.spec.ts`
https://i.imgur.com/idb65NJ.png

Is there anything I am missing?

**Comment by kevinold** [comment]
We have run into similar blockers and are tracking progress on this PR https://github.com/cypress-io/cypress-realworld-app/pull/676 waiting for fixes to Cypress.
