### ISSUE TITLE
Pre-push hook fails after latest commit 2b49dcd

### ISSUE THREAD

**Issue by oppahansi** [cypress-io/cypress-realworld-app#737]
I wanted to update my fork and ran into this issue:

**Pre-push hook fails:**
https://i.imgur.com/Z1QVEu2.png

**Caused by this commit:**
b49dcd
https://i.imgur.com/9sIAEpd.png

You might want to check it out. Reverting the code change on that line fixes it.

Cheers

**Comment by kevinold** [comment]
@oppahansi  This is tested in CI with our `yarn types` command and is passing.  See the "Run yarn types" step on the latest develop run here: https://github.com/cypress-io/cypress-realworld-app/runs/1745605977

I suspect your `node_modules` are old and would recommend removing `node_modules` and starting with a fresh `yarn install`.  This should resolve the issue.
