### ISSUE TITLE
Flaky Branch for Demonstration

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-realworld-app#772]
Branch name: `flake-demo`

- Network Layer
  - Slow API, inconsistent response time
  - Inconsistent responses (data and response code)

- UI Layer
  - Elements not existing
  - Inconsistent delay in display
  
- Application Layer
  - Inconsistent internal state
 
- Visual Flake (low priority)
  - We have examples in Percy. 

## Questions
- How do we keep the branch up to date while maintaining flakiness?
   - It's ok for the app to be out of date since the primary objective is to demonstrate flake.

## Ideas
- Induce failure based on odd or even time (in minutes)

**Comment by kevinold** [comment]
Completed in #862
