### ISSUE TITLE
Mention NPM script for third-party auth services

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-realworld-app#793]
Mention the scripts for the following services in the [readme](https://github.com/cypress-io/cypress-realworld-app#additional-npm-scripts):
- [x] Auth0
- [x] Okta
- [x] Cognito
- [x] Update auth guides to mention the above scripts.

**Comment by kevinold** [comment]
https://github.com/cypress-io/cypress-documentation/pull/3604
