### ISSUE TITLE
Getting error when hitting npm start or yarn start in the terminal. Please help me out.

### ISSUE THREAD

**Issue by vaseemhussain** [cypress-io/cypress-realworld-app#798]
Here is the debug log for the same:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cypress-realworld-app@1.0.0~prestart: cypress-realworld-app@1.0.0
6 verbose lifecycle cypress-realworld-app@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle cypress-realworld-app@1.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;V:\cypress-realworld-app\node_modules\.bin;C:\Program Files (x86)\Microsoft\Edge\Application;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\vasee\AppData\Local\Programs\Python\Python39\;C:\Users\vasee\AppData\Local\Programs\Python\Python39\Scripts;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\vasee\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm 2020.3.2\bin;C:\Users\vasee\AppData\Local\atom\bin;C:\Users\vasee\AppData\Roaming\npm;C:\Users\vasee\AppData\Local\Programs\Microsoft VS Code\bin
8 verbose lifecycle cypress-realworld-app@1.0.0~prestart: CWD: V:\cypress-realworld-app
9 silly lifecycle cypress-realworld-app@1.0.0~prestart: Args: [ '/d /s /c', 'yarn db:seed:dev' ]
10 silly lifecycle cypress-realworld-app@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle cypress-realworld-app@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: cypress-realworld-app@1.0.0 prestart: `yarn db:seed:dev`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid cypress-realworld-app@1.0.0
14 verbose cwd V:\cypress-realworld-app
15 verbose Windows_NT 10.0.18363
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 verbose node v14.15.5
18 verbose npm  v6.14.11
19 error code ELIFECYCLE
20 error errno 1
21 error cypress-realworld-app@1.0.0 prestart: `yarn db:seed:dev`
21 error Exit status 1
22 error Failed at the cypress-realworld-app@1.0.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by kevinold** [comment]
@vaseemhussain

Please try using node v12.20 as listed in the https://github.com/cypress-io/cypress-realworld-app/blob/develop/.node-version

**Comment by vaseemhussain** [comment]
@kevinold Thanks for responding me back.

I did installed node version 12.20 but still I am getting errors when i hit yarn run command.

Here is the error log message that I received:
PS V:\cypress-realworld-app> yarn start
yarn run v1.22.10
$ yarn db:seed:dev
$ yarn predev:cognito:ci
$ yarn copy:mock:awsexports && yarn copy:mock:awsexportses5
$ cp scripts/mock-aws-exports.js src/aws-exports.js
'cp' is not recognized as an internal or external command,
operable program or batch file.

Here is the node version that I am using for this project:
node --version
v12.20.0

**Comment by pbxr250** [comment]
For Windows : cp commands should be changed to copy with escaped backslash in the path and /y in the end:

"copy:mock:awsexports": "copy scripts\\mock-aws-exports.js src\\aws-exports.js /y",
"copy:mock:awsexportses5": "copy scripts\\mock-aws-exports-es5.js aws-exports-es5.js /y",

**Comment by pbxr250** [comment]
For Windows : cp commands should be changed to copy with escaped backslash in the path and /y in the end:

"copy:mock:awsexports": "copy scripts\\\mock-aws-exports.js src\\\aws-exports.js /y",
"copy:mock:awsexportses5": "copy scripts\\\mock-aws-exports-es5.js aws-exports-es5.js /y",
