### ISSUE TITLE
Error during yarn install procedure

### ISSUE THREAD

**Issue by lhimo** [cypress-io/cypress-realworld-app#799]
Executing `yarn install` after cloning the repo gives the following error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.9.1.tgz: ESOCKETTIMEDOUT".
```

Please find the log file attached.
[yarn-error.log](https://github.com/cypress-io/cypress-realworld-app/files/6050394/yarn-error.log)

Executing `yarn dev` afterwards results in:

```
yarn run v1.22.10
warning ..\..\package.json: No license field
$ yarn start:dev
warning ..\..\package.json: No license field
$ yarn db:seed:dev
warning ..\..\package.json: No license field
$ cp src/data/dev-seed.json src/data/database.json
$ NODE_ENV=development start-test start:server-and-api:watch 3000 cypress:open
"NODE_ENV" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kevinold** [comment]
@lhimo 

This is a known issue with installing `@material-ui/icons` and will resolve itself in time.  Keep trying to install every hour or so and refer to the following issues filed against MUI and Yarn for ideas/solutions.


Unable to install @material-ui/icons last version (2.0.1) · Issue #12432 · mui-org/material-ui
https://github.com/mui-org/material-ui/issues/12432

Yarn fails with ESOCKETTIMEDOUT while installing a large package on a slow disk · Issue #8242 · yarnpkg/yarn
https://github.com/yarnpkg/yarn/issues/8242
