### ISSUE TITLE
Cypress Real World App failing

### ISSUE THREAD

**Issue by vanrado** [cypress-io/cypress-realworld-app#922]
Hello there,

please, I am struggling with running the RWA. Installation process went without problems, but when I tried to open the app on `http://localhost:3000`, app fails and following error is in the console:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null.`
An this error is part of what I see in the browser:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

Check the render method of `TransitionGroup`.
▶ 24 stack frames were collapsed.
Module.<anonymous>
c:/Users/raa/workspace/tmp/cypress-realworld-app-1.0.17/cypress-realworld-app-1.0.17/src/index.tsx:95`

My setup:

- Windows 10
- NodeJs v14.16.1
- RWA branch v1.0.17, I tried also develop and error was the same

Please, can you advice me, what I am missing from the installation guide?
Thanks

**Comment by robertguss** [comment]
Hi @vanrado,

Are you still experiencing issues with installation and getting the RWA up and running locally?

**Comment by robertguss** [comment]
Closing this issue since there has not been a response in two weeks.
