### ISSUE TITLE
Logout with Cognito broken

### ISSUE THREAD

**Issue by cunneen** [cypress-io/cypress-realworld-app#998]
Logout with Cognito doesn't work properly; Amplify/Cognito require `Auth.signOut()` (from the `aws-amplify` package) to be called in order to clear the local cookies and storage etc.

Currently logout causes a blank screen, which if the user refreshes the browser they are still logged in.

Attaching an xstate event listener in `AppCognito.tsx` fixes the problem:

```typescript
// replace this import...
// import Amplify from "aws-amplify";
import Amplify, { Auth } from "aws-amplify";

//... inside the functional component:

  useEffect(() => {
    authService.onEvent(async (event) => {
      if (event.type === "done.invoke.performLogout") {
        console.log("AppCognito authService.onEvent done.invoke.performLogout");
        await Auth.signOut();
      }
  }, []);
```

There should perhaps be a more robust test [here](https://github.com/cypress-io/cypress-realworld-app/blob/develop/cypress/tests/ui-auth-providers/cognito.spec.ts#L42) also.

**Comment by kevinold** [comment]
@cunneen Please feel free to open a PR with the changes and we will merge.
